
-- ============================================================================
-- MANNYAM CMS - Content Seed Part 2 (with rich block types matching frontend.html)
-- Uses: Hero, Tiles, Fact Bar, Place Chips, CTA Banner, FAQ
-- Run AFTER seed_content.sql. Uses $$ dollar-quoting.
-- ============================================================================

DELETE FROM public.pages WHERE slug LIKE 'experience-%';

-- ─── EXPERIENCES ─────────────────────────────────────────────────────────────

INSERT INTO public.pages (title, slug, type, status, content, seo_meta) VALUES
('Culture & Heritage', 'experience-heritage', 'Category', 'Published',
$$[{"id":"e1-hero","type":"Hero","data":{"headline":"Culture & Heritage","subheadline":"Walk the old quarters where centuries still shape daily life, on foot, by cycle or by tuk-tuk.","backgroundImage":"","ctaText":"Plan This Experience","ctaLink":"/enquire"}},{"id":"e1-tiles","type":"Tiles","data":{"heading":"What you might do","tiles":[{"title":"Heritage walks","description":"Hidden lanes, carved facades and the stories behind them."},{"title":"Royal pasts","description":"Forts and palaces, with the families who keep them."},{"title":"Living traditions","description":"Crafts and rituals still practised by hand."}]}},{"id":"e1-places","type":"Place Chips","data":{"heading":"Best enjoyed in","places":[{"name":"Jaipur","region":"Rajasthan"},{"name":"Udaipur","region":"Rajasthan"},{"name":"Madurai","region":"Tamil Nadu"}]}},{"id":"e1-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"What kinds of experiences can I have in India?","answer":"From culture and heritage to food, wildlife, spiritual travel, royal evenings and honeymoons, our India experiences let you travel by the feeling you are after. Each one is private and tailor-made."},{"question":"Can I combine different experiences in one trip?","answer":"Yes, and most travellers do. We weave heritage, food, nature and quiet time into a single journey that flows at your pace, rather than a fixed package."},{"question":"Can I customise a ready-made journey?","answer":"Yes. Every journey is a starting point. Adjust the route, pace, stays and experiences with your curator until it feels entirely your own."},{"question":"Are flights and hotels included?","answer":"Journeys include carefully chosen stays, private transport, guides and the experiences described. We can also arrange internal flights and advise on international ones."}]}},{"id":"e1-cta","type":"CTA Banner","data":{"headline":"Make it yours","body":"Every experience is shaped around your pace and your people. Tell us what you have in mind.","buttonLabel":"Design this experience","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"Culture & Heritage | MANNYAM","description":"Walk the old quarters where centuries still shape daily life, on foot, by cycle or by tuk-tuk.","canonical_url":"https://mannyam.in/experience-heritage"}$$::jsonb),

('Local Life & Community', 'experience-local-life', 'Category', 'Published',
$$[{"id":"e2-hero","type":"Hero","data":{"headline":"Local Life & Community","subheadline":"Meet India through its people, in villages, homes and on short local train journeys.","backgroundImage":"","ctaText":"Plan This Experience","ctaLink":"/enquire"}},{"id":"e2-tiles","type":"Tiles","data":{"heading":"What you might do","tiles":[{"title":"Home meals","description":"Shared food and easy conversation in a family home."},{"title":"Village days","description":"Rural walks and women led initiatives, warm and human."},{"title":"Slow trains","description":"A short ride alongside locals, the real countryside passing by."}]}},{"id":"e2-places","type":"Place Chips","data":{"heading":"Best enjoyed in","places":[{"name":"Kutch","region":"Gujarat"},{"name":"Wayanad","region":"Kerala"},{"name":"Khasi Hills","region":"Meghalaya"}]}},{"id":"e2-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"What kinds of experiences can I have in India?","answer":"From culture and heritage to food, wildlife, spiritual travel, royal evenings and honeymoons, our India experiences let you travel by the feeling you are after. Each one is private and tailor-made."},{"question":"Can I combine different experiences in one trip?","answer":"Yes, and most travellers do. We weave heritage, food, nature and quiet time into a single journey that flows at your pace, rather than a fixed package."},{"question":"Can I customise a ready-made journey?","answer":"Yes. Every journey is a starting point. Adjust the route, pace, stays and experiences with your curator until it feels entirely your own."},{"question":"Are flights and hotels included?","answer":"Journeys include carefully chosen stays, private transport, guides and the experiences described. We can also arrange internal flights and advise on international ones."}]}},{"id":"e2-cta","type":"CTA Banner","data":{"headline":"Make it yours","body":"Every experience is shaped around your pace and your people. Tell us what you have in mind.","buttonLabel":"Design this experience","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"Local Life & Community | MANNYAM","description":"Meet India through its people, in villages, homes and on short local train journeys.","canonical_url":"https://mannyam.in/experience-local-life"}$$::jsonb),

('Food & Culinary Stories', 'experience-food', 'Category', 'Published',
$$[{"id":"e3-hero","type":"Hero","data":{"headline":"Food & Culinary Stories","subheadline":"Every meal tells a story of geography, history and tradition. Taste your way through it.","backgroundImage":"","ctaText":"Plan This Experience","ctaLink":"/enquire"}},{"id":"e3-tiles","type":"Tiles","data":{"heading":"What you might do","tiles":[{"title":"Food walks","description":"Street kitchens and market stalls with someone who knows them."},{"title":"Cook and dine","description":"A hands-on lesson, then a long table with the family."},{"title":"Regional tables","description":"From coastal spice to royal kitchens, region by region."}]}},{"id":"e3-places","type":"Place Chips","data":{"heading":"Best enjoyed in","places":[{"name":"Old Delhi","region":"Delhi"},{"name":"Chettinad","region":"Tamil Nadu"},{"name":"Lucknow","region":"Uttar Pradesh"}]}},{"id":"e3-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"What kinds of experiences can I have in India?","answer":"From culture and heritage to food, wildlife, spiritual travel, royal evenings and honeymoons, our India experiences let you travel by the feeling you are after. Each one is private and tailor-made."},{"question":"Can I combine different experiences in one trip?","answer":"Yes, and most travellers do. We weave heritage, food, nature and quiet time into a single journey that flows at your pace, rather than a fixed package."},{"question":"Can I customise a ready-made journey?","answer":"Yes. Every journey is a starting point. Adjust the route, pace, stays and experiences with your curator until it feels entirely your own."},{"question":"Are flights and hotels included?","answer":"Journeys include carefully chosen stays, private transport, guides and the experiences described. We can also arrange internal flights and advise on international ones."}]}},{"id":"e3-cta","type":"CTA Banner","data":{"headline":"Make it yours","body":"Every experience is shaped around your pace and your people. Tell us what you have in mind.","buttonLabel":"Design this experience","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"Food & Culinary Stories | MANNYAM","description":"Every meal tells a story of geography, history and tradition. Taste your way through it.","canonical_url":"https://mannyam.in/experience-food"}$$::jsonb),

('Spiritual & Soulful', 'experience-spiritual', 'Category', 'Published',
$$[{"id":"e4-hero","type":"Hero","data":{"headline":"Spiritual & Soulful","subheadline":"Witness rituals that have flowed unchanged for centuries, and find a little quiet of your own.","backgroundImage":"","ctaText":"Plan This Experience","ctaLink":"/enquire"}},{"id":"e4-tiles","type":"Tiles","data":{"heading":"What you might do","tiles":[{"title":"River dawns","description":"Yoga and prayer by sacred water as the day begins."},{"title":"Ceremonial boats","description":"A slow row at dusk, with live music on the water."},{"title":"Temples and ghats","description":"Time with priests and practitioners, gently guided."}]}},{"id":"e4-places","type":"Place Chips","data":{"heading":"Best enjoyed in","places":[{"name":"Rishikesh","region":"Uttarakhand"},{"name":"Varanasi","region":"Uttar Pradesh"},{"name":"Madurai","region":"Tamil Nadu"}]}},{"id":"e4-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"What kinds of experiences can I have in India?","answer":"From culture and heritage to food, wildlife, spiritual travel, royal evenings and honeymoons, our India experiences let you travel by the feeling you are after. Each one is private and tailor-made."},{"question":"Can I combine different experiences in one trip?","answer":"Yes, and most travellers do. We weave heritage, food, nature and quiet time into a single journey that flows at your pace, rather than a fixed package."},{"question":"Can I customise a ready-made journey?","answer":"Yes. Every journey is a starting point. Adjust the route, pace, stays and experiences with your curator until it feels entirely your own."},{"question":"Are flights and hotels included?","answer":"Journeys include carefully chosen stays, private transport, guides and the experiences described. We can also arrange internal flights and advise on international ones."}]}},{"id":"e4-cta","type":"CTA Banner","data":{"headline":"Make it yours","body":"Every experience is shaped around your pace and your people. Tell us what you have in mind.","buttonLabel":"Design this experience","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"Spiritual & Soulful | MANNYAM","description":"Witness rituals that have flowed unchanged for centuries, and find a little quiet of your own.","canonical_url":"https://mannyam.in/experience-spiritual"}$$::jsonb),

('Nature & Wildlife', 'experience-wildlife', 'Category', 'Published',
$$[{"id":"e5-hero","type":"Hero","data":{"headline":"Nature & Wildlife","subheadline":"Reconnect with the wild through careful, responsible encounters led by expert naturalists.","backgroundImage":"","ctaText":"Plan This Experience","ctaLink":"/enquire"}},{"id":"e5-tiles","type":"Tiles","data":{"heading":"What you might do","tiles":[{"title":"Tiger country","description":"Dawn drives in the great national parks."},{"title":"Plantation walks","description":"Tea and spice trails through deep green hills."},{"title":"Jungle table","description":"Lunch in the forest after a morning safari."}]}},{"id":"e5-places","type":"Place Chips","data":{"heading":"Best enjoyed in","places":[{"name":"Ranthambore","region":"Rajasthan"},{"name":"Kaziranga","region":"Assam"},{"name":"Periyar","region":"Kerala"}]}},{"id":"e5-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"What kinds of experiences can I have in India?","answer":"From culture and heritage to food, wildlife, spiritual travel, royal evenings and honeymoons, our India experiences let you travel by the feeling you are after. Each one is private and tailor-made."},{"question":"Can I combine different experiences in one trip?","answer":"Yes, and most travellers do. We weave heritage, food, nature and quiet time into a single journey that flows at your pace, rather than a fixed package."},{"question":"Can I customise a ready-made journey?","answer":"Yes. Every journey is a starting point. Adjust the route, pace, stays and experiences with your curator until it feels entirely your own."},{"question":"Are flights and hotels included?","answer":"Journeys include carefully chosen stays, private transport, guides and the experiences described. We can also arrange internal flights and advise on international ones."}]}},{"id":"e5-cta","type":"CTA Banner","data":{"headline":"Make it yours","body":"Every experience is shaped around your pace and your people. Tell us what you have in mind.","buttonLabel":"Design this experience","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"Nature & Wildlife | MANNYAM","description":"Reconnect with the wild through careful, responsible encounters led by expert naturalists.","canonical_url":"https://mannyam.in/experience-wildlife"}$$::jsonb),

('Royal & Exclusive', 'experience-royal', 'Category', 'Published',
$$[{"id":"e6-hero","type":"Hero","data":{"headline":"Royal & Exclusive","subheadline":"Step into India's regal past with moments once reserved for royalty alone.","backgroundImage":"","ctaText":"Plan This Experience","ctaLink":"/enquire"}},{"id":"e6-tiles","type":"Tiles","data":{"heading":"What you might do","tiles":[{"title":"Vintage drives","description":"A classic car through the old city at golden hour."},{"title":"Lakeside high tea","description":"An exclusive table set just for you."},{"title":"Private dinners","description":"A historic courtyard, candlelight and nobody else."}]}},{"id":"e6-places","type":"Place Chips","data":{"heading":"Best enjoyed in","places":[{"name":"Udaipur","region":"Rajasthan"},{"name":"Jodhpur","region":"Rajasthan"},{"name":"Mysuru","region":"Karnataka"}]}},{"id":"e6-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"What kinds of experiences can I have in India?","answer":"From culture and heritage to food, wildlife, spiritual travel, royal evenings and honeymoons, our India experiences let you travel by the feeling you are after. Each one is private and tailor-made."},{"question":"Can I combine different experiences in one trip?","answer":"Yes, and most travellers do. We weave heritage, food, nature and quiet time into a single journey that flows at your pace, rather than a fixed package."},{"question":"Can I customise a ready-made journey?","answer":"Yes. Every journey is a starting point. Adjust the route, pace, stays and experiences with your curator until it feels entirely your own."},{"question":"Are flights and hotels included?","answer":"Journeys include carefully chosen stays, private transport, guides and the experiences described. We can also arrange internal flights and advise on international ones."}]}},{"id":"e6-cta","type":"CTA Banner","data":{"headline":"Make it yours","body":"Every experience is shaped around your pace and your people. Tell us what you have in mind.","buttonLabel":"Design this experience","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"Royal & Exclusive | MANNYAM","description":"Step into India's regal past with moments once reserved for royalty alone.","canonical_url":"https://mannyam.in/experience-royal"}$$::jsonb),

('Arts, Music & Performance', 'experience-arts', 'Category', 'Published',
$$[{"id":"e7-hero","type":"Hero","data":{"headline":"Arts, Music & Performance","subheadline":"Discover India's creative soul, from classical musicians to regional dance and martial forms.","backgroundImage":"","ctaText":"Plan This Experience","ctaLink":"/enquire"}},{"id":"e7-tiles","type":"Tiles","data":{"heading":"What you might do","tiles":[{"title":"Private recitals","description":"An intimate performance by masters of a classical form."},{"title":"Art districts","description":"The studios and lanes where India still makes by hand."},{"title":"Stage traditions","description":"Kathakali, Kalbeliya and more, up close."}]}},{"id":"e7-places","type":"Place Chips","data":{"heading":"Best enjoyed in","places":[{"name":"Kochi","region":"Kerala"},{"name":"Jaipur","region":"Rajasthan"},{"name":"Kolkata","region":"West Bengal"}]}},{"id":"e7-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"What kinds of experiences can I have in India?","answer":"From culture and heritage to food, wildlife, spiritual travel, royal evenings and honeymoons, our India experiences let you travel by the feeling you are after. Each one is private and tailor-made."},{"question":"Can I combine different experiences in one trip?","answer":"Yes, and most travellers do. We weave heritage, food, nature and quiet time into a single journey that flows at your pace, rather than a fixed package."},{"question":"Can I customise a ready-made journey?","answer":"Yes. Every journey is a starting point. Adjust the route, pace, stays and experiences with your curator until it feels entirely your own."},{"question":"Are flights and hotels included?","answer":"Journeys include carefully chosen stays, private transport, guides and the experiences described. We can also arrange internal flights and advise on international ones."}]}},{"id":"e7-cta","type":"CTA Banner","data":{"headline":"Make it yours","body":"Every experience is shaped around your pace and your people. Tell us what you have in mind.","buttonLabel":"Design this experience","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"Arts, Music & Performance | MANNYAM","description":"Discover India's creative soul, from classical musicians to regional dance and martial forms.","canonical_url":"https://mannyam.in/experience-arts"}$$::jsonb),

('Slow Travel & Scenic Living', 'experience-slow', 'Category', 'Published',
$$[{"id":"e8-hero","type":"Hero","data":{"headline":"Slow Travel & Scenic Living","subheadline":"Sometimes the best way to know a place is to slow right down and let it unfold.","backgroundImage":"","ctaText":"Plan This Experience","ctaLink":"/enquire"}},{"id":"e8-tiles","type":"Tiles","data":{"heading":"What you might do","tiles":[{"title":"Sunset cruises","description":"A quiet boat as the light turns on the water."},{"title":"Markets after dark","description":"The old town once the day's heat has gone."},{"title":"Cycle the towns","description":"Heritage streets at the pace of a bicycle."}]}},{"id":"e8-places","type":"Place Chips","data":{"heading":"Best enjoyed in","places":[{"name":"Pondicherry","region":"Tamil Nadu"},{"name":"Fort Kochi","region":"Kerala"},{"name":"Alleppey","region":"Kerala"}]}},{"id":"e8-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"What kinds of experiences can I have in India?","answer":"From culture and heritage to food, wildlife, spiritual travel, royal evenings and honeymoons, our India experiences let you travel by the feeling you are after. Each one is private and tailor-made."},{"question":"Can I combine different experiences in one trip?","answer":"Yes, and most travellers do. We weave heritage, food, nature and quiet time into a single journey that flows at your pace, rather than a fixed package."},{"question":"Can I customise a ready-made journey?","answer":"Yes. Every journey is a starting point. Adjust the route, pace, stays and experiences with your curator until it feels entirely your own."},{"question":"Are flights and hotels included?","answer":"Journeys include carefully chosen stays, private transport, guides and the experiences described. We can also arrange internal flights and advise on international ones."}]}},{"id":"e8-cta","type":"CTA Banner","data":{"headline":"Make it yours","body":"Every experience is shaped around your pace and your people. Tell us what you have in mind.","buttonLabel":"Design this experience","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"Slow Travel & Scenic Living | MANNYAM","description":"Sometimes the best way to know a place is to slow right down and let it unfold.","canonical_url":"https://mannyam.in/experience-slow"}$$::jsonb),

('Honeymoon & Romance', 'experience-honeymoon', 'Category', 'Published',
$$[{"id":"e9-hero","type":"Hero","data":{"headline":"Honeymoon & Romance","subheadline":"However you picture it, India sets the scene for romance like nowhere else.","backgroundImage":"","ctaText":"Plan This Experience","ctaLink":"/enquire"}},{"id":"e9-tiles","type":"Tiles","data":{"heading":"What you might do","tiles":[{"title":"Lake palaces","description":"A suite on the water and a boat to a private dinner."},{"title":"Desert nights","description":"Sundowners on the dunes and a sky full of stars."},{"title":"Backwater calm","description":"Just the two of you, drifting, with your own cook."}]}},{"id":"e9-places","type":"Place Chips","data":{"heading":"Best enjoyed in","places":[{"name":"Udaipur","region":"Rajasthan"},{"name":"Jaisalmer","region":"Rajasthan"},{"name":"Alleppey","region":"Kerala"}]}},{"id":"e9-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"What kinds of experiences can I have in India?","answer":"From culture and heritage to food, wildlife, spiritual travel, royal evenings and honeymoons, our India experiences let you travel by the feeling you are after. Each one is private and tailor-made."},{"question":"Can I combine different experiences in one trip?","answer":"Yes, and most travellers do. We weave heritage, food, nature and quiet time into a single journey that flows at your pace, rather than a fixed package."},{"question":"Can I customise a ready-made journey?","answer":"Yes. Every journey is a starting point. Adjust the route, pace, stays and experiences with your curator until it feels entirely your own."},{"question":"Are flights and hotels included?","answer":"Journeys include carefully chosen stays, private transport, guides and the experiences described. We can also arrange internal flights and advise on international ones."}]}},{"id":"e9-cta","type":"CTA Banner","data":{"headline":"Make it yours","body":"Every experience is shaped around your pace and your people. Tell us what you have in mind.","buttonLabel":"Design this experience","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"Honeymoon & Romance | MANNYAM","description":"However you picture it, India sets the scene for romance like nowhere else.","canonical_url":"https://mannyam.in/experience-honeymoon"}$$::jsonb);

DELETE FROM public.pages WHERE slug LIKE 'festival-%';

-- ─── FESTIVALS ───────────────────────────────────────────────────────────────

INSERT INTO public.pages (title, slug, type, status, content, seo_meta) VALUES
('Holi', 'festival-holi', 'Category', 'Published',
$$[{"id":"f1-hero","type":"Hero","data":{"headline":"Holi","subheadline":"The festival of colour, love and spring. A morning that turns whole towns into a swirl of pink, gold and laughter.","backgroundImage":"","ctaText":"Plan My Journey","ctaLink":"/enquire"}},{"id":"f1-facts","type":"Fact Bar","data":{"facts":[{"label":"When","value":"March"},{"label":"Where","value":"Mathura, Vrindavan and Barsana, Uttar Pradesh; Jaipur and Udaipur, Rajasthan"}]}},{"id":"f1-tiles","type":"Tiles","data":{"heading":"How we celebrate it with you","tiles":[{"title":"The colour throw","description":"Join the crowds, or watch from a calm rooftop, as colour fills the air."},{"title":"Barsana traditions","description":"The famous, joyful Lathmar Holi in the towns near Mathura."},{"title":"A gentler Holi","description":"A private, family style celebration if the crowds feel too much."}]}},{"id":"f1-places","type":"Place Chips","data":{"heading":"Best cities","places":[{"name":"Mathura","region":"Uttar Pradesh"},{"name":"Vrindavan","region":"Uttar Pradesh"},{"name":"Barsana","region":"Uttar Pradesh"},{"name":"Jaipur","region":"Rajasthan"},{"name":"Udaipur","region":"Rajasthan"},{"name":"Pushkar","region":"Rajasthan"}]}},{"id":"f1-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"Are festivals in India safe for travellers?","answer":"Yes, when planned correctly. We ensure you experience the joy of the festival while staying comfortable, with vetted guides, private transport and carefully chosen viewing spots."},{"question":"How far in advance should I plan a festival trip?","answer":"At least six to nine months. The best heritage stays and guides book out quickly around major festivals like Holi and Diwali."},{"question":"Will it be too crowded?","answer":"Festivals are busy, but we balance the energy of the crowds with quiet retreats. You can join the heart of the action when you want, and step back when you need to."},{"question":"Can I combine a festival with a longer journey?","answer":"Absolutely. A festival is often the focal point of a longer journey through India, giving you a balance of celebration and slow travel."}]}},{"id":"f1-cta","type":"CTA Banner","data":{"headline":"Join the celebration","body":"We arrange the timing and details. Tell us your travel window.","buttonLabel":"Plan my journey","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"Holi | MANNYAM","description":"The festival of colour, love and spring. A morning that turns whole towns into a swirl of pink, gold and laughter.","canonical_url":"https://mannyam.in/festival-holi"}$$::jsonb),

('Diwali', 'festival-diwali', 'Category', 'Published',
$$[{"id":"f2-hero","type":"Hero","data":{"headline":"Diwali","subheadline":"The festival of lights. Lamps along every doorway, fireworks over the rivers and a warmth that fills the night.","backgroundImage":"","ctaText":"Plan My Journey","ctaLink":"/enquire"}},{"id":"f2-facts","type":"Fact Bar","data":{"facts":[{"label":"When","value":"October to November"},{"label":"Where","value":"Varanasi, Uttar Pradesh; Jaipur and Udaipur, Rajasthan; Amritsar, Punjab"}]}},{"id":"f2-tiles","type":"Tiles","data":{"heading":"How we celebrate it with you","tiles":[{"title":"Lamp lit ghats","description":"Thousands of oil lamps float and glow along the river at Varanasi."},{"title":"City of light","description":"Jaipur and Udaipur dressed head to toe in light and colour."},{"title":"A family Diwali","description":"Sweets, prayers and lamps in a home that welcomes you in."}]}},{"id":"f2-places","type":"Place Chips","data":{"heading":"Best cities","places":[{"name":"Varanasi","region":"Uttar Pradesh"},{"name":"Jaipur","region":"Rajasthan"},{"name":"Udaipur","region":"Rajasthan"},{"name":"Amritsar","region":"Punjab"}]}},{"id":"f2-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"Are festivals in India safe for travellers?","answer":"Yes, when planned correctly. We ensure you experience the joy of the festival while staying comfortable, with vetted guides, private transport and carefully chosen viewing spots."},{"question":"How far in advance should I plan a festival trip?","answer":"At least six to nine months. The best heritage stays and guides book out quickly around major festivals like Holi and Diwali."},{"question":"Will it be too crowded?","answer":"Festivals are busy, but we balance the energy of the crowds with quiet retreats. You can join the heart of the action when you want, and step back when you need to."},{"question":"Can I combine a festival with a longer journey?","answer":"Absolutely. A festival is often the focal point of a longer journey through India, giving you a balance of celebration and slow travel."}]}},{"id":"f2-cta","type":"CTA Banner","data":{"headline":"Join the celebration","body":"We arrange the timing and details. Tell us your travel window.","buttonLabel":"Plan my journey","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"Diwali | MANNYAM","description":"The festival of lights. Lamps along every doorway, fireworks over the rivers and a warmth that fills the night.","canonical_url":"https://mannyam.in/festival-diwali"}$$::jsonb),

('Dussehra', 'festival-dussehra', 'Category', 'Published',
$$[{"id":"f3-hero","type":"Hero","data":{"headline":"Dussehra","subheadline":"The triumph of good over evil, marked by royal processions, towering effigies and ancient street theatre.","backgroundImage":"","ctaText":"Plan My Journey","ctaLink":"/enquire"}},{"id":"f3-facts","type":"Fact Bar","data":{"facts":[{"label":"When","value":"October"},{"label":"Where","value":"Mysuru, Karnataka; Kullu, Himachal Pradesh; Varanasi Ramlila"}]}},{"id":"f3-tiles","type":"Tiles","data":{"heading":"How we celebrate it with you","tiles":[{"title":"Mysuru Dasara","description":"The lit palace and a grand procession of elephants and music."},{"title":"Kullu's gods","description":"Hundreds of village deities carried together through the valley."},{"title":"Ramlila nights","description":"The old retelling of the Ramayana, performed across the city."}]}},{"id":"f3-places","type":"Place Chips","data":{"heading":"Best cities","places":[{"name":"Mysuru","region":"Karnataka"},{"name":"Kullu","region":"Himachal Pradesh"},{"name":"Varanasi","region":"Uttar Pradesh"}]}},{"id":"f3-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"Are festivals in India safe for travellers?","answer":"Yes, when planned correctly. We ensure you experience the joy of the festival while staying comfortable, with vetted guides, private transport and carefully chosen viewing spots."},{"question":"How far in advance should I plan a festival trip?","answer":"At least six to nine months. The best heritage stays and guides book out quickly around major festivals like Holi and Diwali."},{"question":"Will it be too crowded?","answer":"Festivals are busy, but we balance the energy of the crowds with quiet retreats. You can join the heart of the action when you want, and step back when you need to."},{"question":"Can I combine a festival with a longer journey?","answer":"Absolutely. A festival is often the focal point of a longer journey through India, giving you a balance of celebration and slow travel."}]}},{"id":"f3-cta","type":"CTA Banner","data":{"headline":"Join the celebration","body":"We arrange the timing and details. Tell us your travel window.","buttonLabel":"Plan my journey","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"Dussehra | MANNYAM","description":"The triumph of good over evil, marked by royal processions, towering effigies and ancient street theatre.","canonical_url":"https://mannyam.in/festival-dussehra"}$$::jsonb),

('Durga Puja', 'festival-durga-puja', 'Category', 'Published',
$$[{"id":"f4-hero","type":"Hero","data":{"headline":"Durga Puja","subheadline":"The east at its most artistic. Whole neighbourhoods become open air galleries of light, sculpture and devotion.","backgroundImage":"","ctaText":"Plan My Journey","ctaLink":"/enquire"}},{"id":"f4-facts","type":"Fact Bar","data":{"facts":[{"label":"When","value":"October"},{"label":"Where","value":"Kolkata, West Bengal"}]}},{"id":"f4-tiles","type":"Tiles","data":{"heading":"How we celebrate it with you","tiles":[{"title":"Pandal hopping","description":"Walk between extraordinary temporary art pavilions, each one different."},{"title":"The drums","description":"Live dhak drumming and dance that builds for days."},{"title":"River farewell","description":"The final, moving procession to the water."}]}},{"id":"f4-places","type":"Place Chips","data":{"heading":"Best cities","places":[{"name":"Kolkata","region":"West Bengal"}]}},{"id":"f4-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"Are festivals in India safe for travellers?","answer":"Yes, when planned correctly. We ensure you experience the joy of the festival while staying comfortable, with vetted guides, private transport and carefully chosen viewing spots."},{"question":"How far in advance should I plan a festival trip?","answer":"At least six to nine months. The best heritage stays and guides book out quickly around major festivals like Holi and Diwali."},{"question":"Will it be too crowded?","answer":"Festivals are busy, but we balance the energy of the crowds with quiet retreats. You can join the heart of the action when you want, and step back when you need to."},{"question":"Can I combine a festival with a longer journey?","answer":"Absolutely. A festival is often the focal point of a longer journey through India, giving you a balance of celebration and slow travel."}]}},{"id":"f4-cta","type":"CTA Banner","data":{"headline":"Join the celebration","body":"We arrange the timing and details. Tell us your travel window.","buttonLabel":"Plan my journey","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"Durga Puja | MANNYAM","description":"The east at its most artistic. Whole neighbourhoods become open air galleries of light, sculpture and devotion.","canonical_url":"https://mannyam.in/festival-durga-puja"}$$::jsonb),

('Navratri & Garba', 'festival-navratri', 'Category', 'Published',
$$[{"id":"f5-hero","type":"Hero","data":{"headline":"Navratri & Garba","subheadline":"Nine nights of rhythm. Great circles of dancers in mirror work and colour, turning until the early hours.","backgroundImage":"","ctaText":"Plan My Journey","ctaLink":"/enquire"}},{"id":"f5-facts","type":"Fact Bar","data":{"facts":[{"label":"When","value":"October"},{"label":"Where","value":"Ahmedabad and Vadodara, Gujarat"}]}},{"id":"f5-tiles","type":"Tiles","data":{"heading":"How we celebrate it with you","tiles":[{"title":"Learn the steps","description":"A gentle lesson before you join the circle yourself."},{"title":"The big grounds","description":"The energy of thousands dancing Garba and Dandiya together."},{"title":"Dress the part","description":"Traditional outfits arranged, so you feel part of it all."}]}},{"id":"f5-places","type":"Place Chips","data":{"heading":"Best cities","places":[{"name":"Ahmedabad","region":"Gujarat"},{"name":"Vadodara","region":"Gujarat"}]}},{"id":"f5-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"Are festivals in India safe for travellers?","answer":"Yes, when planned correctly. We ensure you experience the joy of the festival while staying comfortable, with vetted guides, private transport and carefully chosen viewing spots."},{"question":"How far in advance should I plan a festival trip?","answer":"At least six to nine months. The best heritage stays and guides book out quickly around major festivals like Holi and Diwali."},{"question":"Will it be too crowded?","answer":"Festivals are busy, but we balance the energy of the crowds with quiet retreats. You can join the heart of the action when you want, and step back when you need to."},{"question":"Can I combine a festival with a longer journey?","answer":"Absolutely. A festival is often the focal point of a longer journey through India, giving you a balance of celebration and slow travel."}]}},{"id":"f5-cta","type":"CTA Banner","data":{"headline":"Join the celebration","body":"We arrange the timing and details. Tell us your travel window.","buttonLabel":"Plan my journey","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"Navratri & Garba | MANNYAM","description":"Nine nights of rhythm. Great circles of dancers in mirror work and colour, turning until the early hours.","canonical_url":"https://mannyam.in/festival-navratri"}$$::jsonb),

('Ganesh Chaturthi', 'festival-ganesh-chaturthi', 'Category', 'Published',
$$[{"id":"f6-hero","type":"Hero","data":{"headline":"Ganesh Chaturthi","subheadline":"Mumbai's biggest celebration. Streets full of music and colour as the elephant headed god is welcomed and, days later, sent to the sea.","backgroundImage":"","ctaText":"Plan My Journey","ctaLink":"/enquire"}},{"id":"f6-facts","type":"Fact Bar","data":{"facts":[{"label":"When","value":"August to September"},{"label":"Where","value":"Mumbai and the Konkan coast, Maharashtra"}]}},{"id":"f6-tiles","type":"Tiles","data":{"heading":"How we celebrate it with you","tiles":[{"title":"Welcome days","description":"Beautifully made idols and the joy of the opening processions."},{"title":"Coastal Konkan","description":"A quieter, village side of the festival along the coast."},{"title":"To the water","description":"The final procession to the sea, vast and full of feeling."}]}},{"id":"f6-places","type":"Place Chips","data":{"heading":"Best cities","places":[{"name":"Mumbai","region":"Maharashtra"},{"name":"Pune","region":"Maharashtra"}]}},{"id":"f6-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"Are festivals in India safe for travellers?","answer":"Yes, when planned correctly. We ensure you experience the joy of the festival while staying comfortable, with vetted guides, private transport and carefully chosen viewing spots."},{"question":"How far in advance should I plan a festival trip?","answer":"At least six to nine months. The best heritage stays and guides book out quickly around major festivals like Holi and Diwali."},{"question":"Will it be too crowded?","answer":"Festivals are busy, but we balance the energy of the crowds with quiet retreats. You can join the heart of the action when you want, and step back when you need to."},{"question":"Can I combine a festival with a longer journey?","answer":"Absolutely. A festival is often the focal point of a longer journey through India, giving you a balance of celebration and slow travel."}]}},{"id":"f6-cta","type":"CTA Banner","data":{"headline":"Join the celebration","body":"We arrange the timing and details. Tell us your travel window.","buttonLabel":"Plan my journey","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"Ganesh Chaturthi | MANNYAM","description":"Mumbai's biggest celebration. Streets full of music and colour as the elephant headed god is welcomed and, days later, sent to the sea.","canonical_url":"https://mannyam.in/festival-ganesh-chaturthi"}$$::jsonb),

('Pongal & Onam', 'festival-harvest', 'Category', 'Published',
$$[{"id":"f7-hero","type":"Hero","data":{"headline":"Pongal & Onam","subheadline":"The south gives thanks. Floral carpets, boat races and feasts served on banana leaves, all rooted in the land.","backgroundImage":"","ctaText":"Plan My Journey","ctaLink":"/enquire"}},{"id":"f7-facts","type":"Fact Bar","data":{"facts":[{"label":"When","value":"January and August"},{"label":"Where","value":"Tamil Nadu (Pongal) and Kerala (Onam)"}]}},{"id":"f7-tiles","type":"Tiles","data":{"heading":"How we celebrate it with you","tiles":[{"title":"Onam feast","description":"The grand Sadhya, dish after dish on a fresh banana leaf."},{"title":"Flower carpets","description":"Intricate Pookalam laid out across doorways and courtyards."},{"title":"Snake boats","description":"The thunder of Kerala's long racing boats on the water."}]}},{"id":"f7-places","type":"Place Chips","data":{"heading":"Best cities","places":[{"name":"Madurai","region":"Tamil Nadu"},{"name":"Kochi","region":"Kerala"},{"name":"Alleppey","region":"Kerala"}]}},{"id":"f7-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"Are festivals in India safe for travellers?","answer":"Yes, when planned correctly. We ensure you experience the joy of the festival while staying comfortable, with vetted guides, private transport and carefully chosen viewing spots."},{"question":"How far in advance should I plan a festival trip?","answer":"At least six to nine months. The best heritage stays and guides book out quickly around major festivals like Holi and Diwali."},{"question":"Will it be too crowded?","answer":"Festivals are busy, but we balance the energy of the crowds with quiet retreats. You can join the heart of the action when you want, and step back when you need to."},{"question":"Can I combine a festival with a longer journey?","answer":"Absolutely. A festival is often the focal point of a longer journey through India, giving you a balance of celebration and slow travel."}]}},{"id":"f7-cta","type":"CTA Banner","data":{"headline":"Join the celebration","body":"We arrange the timing and details. Tell us your travel window.","buttonLabel":"Plan my journey","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"Pongal & Onam | MANNYAM","description":"The south gives thanks. Floral carpets, boat races and feasts served on banana leaves, all rooted in the land.","canonical_url":"https://mannyam.in/festival-harvest"}$$::jsonb),

('Celebration Shows', 'festival-celebration-shows', 'Category', 'Published',
$$[{"id":"f8-hero","type":"Hero","data":{"headline":"Celebration Shows","subheadline":"You do not have to wait for a festival to feel the celebration. Private evenings of folk dance, music and fire, arranged just for you.","backgroundImage":"","ctaText":"Plan My Journey","ctaLink":"/enquire"}},{"id":"f8-facts","type":"Fact Bar","data":{"facts":[{"label":"When","value":"All year"},{"label":"Where","value":"Rajasthan, Kerala, Gujarat and beyond"}]}},{"id":"f8-tiles","type":"Tiles","data":{"heading":"How we celebrate it with you","tiles":[{"title":"Desert evenings","description":"Kalbeliya dancers and folk musicians under a Rajasthani sky."},{"title":"Kathakali up close","description":"The painted faces and slow drama of Kerala's great art form."},{"title":"Light and fire","description":"Drummers, lamps and movement, set in a courtyard or fort."}]}},{"id":"f8-places","type":"Place Chips","data":{"heading":"Best cities","places":[{"name":"Jaisalmer","region":"Rajasthan"},{"name":"Kochi","region":"Kerala"},{"name":"Udaipur","region":"Rajasthan"}]}},{"id":"f8-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"Are festivals in India safe for travellers?","answer":"Yes, when planned correctly. We ensure you experience the joy of the festival while staying comfortable, with vetted guides, private transport and carefully chosen viewing spots."},{"question":"How far in advance should I plan a festival trip?","answer":"At least six to nine months. The best heritage stays and guides book out quickly around major festivals like Holi and Diwali."},{"question":"Will it be too crowded?","answer":"Festivals are busy, but we balance the energy of the crowds with quiet retreats. You can join the heart of the action when you want, and step back when you need to."},{"question":"Can I combine a festival with a longer journey?","answer":"Absolutely. A festival is often the focal point of a longer journey through India, giving you a balance of celebration and slow travel."}]}},{"id":"f8-cta","type":"CTA Banner","data":{"headline":"Join the celebration","body":"We arrange the timing and details. Tell us your travel window.","buttonLabel":"Plan my journey","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"Celebration Shows | MANNYAM","description":"You do not have to wait for a festival to feel the celebration. Private evenings of folk dance, music and fire, arranged just for you.","canonical_url":"https://mannyam.in/festival-celebration-shows"}$$::jsonb);

DELETE FROM public.pages WHERE slug LIKE 'destination-%';

-- ─── DESTINATIONS ────────────────────────────────────────────────────────────

INSERT INTO public.pages (title, slug, type, status, content, seo_meta) VALUES
('Rajasthan', 'destination-rajasthan', 'Category', 'Published',
$$[{"id":"d1-hero","type":"Hero","data":{"headline":"Rajasthan","subheadline":"The India of the imagination. Warrior forts, lake palaces and bazaars that have traded for centuries.","backgroundImage":"","ctaText":"Plan My Journey","ctaLink":"/enquire"}},{"id":"d1-facts","type":"Fact Bar","data":{"facts":[{"label":"Best season","value":"October to March"}]}},{"id":"d1-tiles","type":"Tiles","data":{"heading":"What you might do","tiles":[{"title":"Palace stays","description":"Sleep within working palaces in Udaipur and Jaipur."},{"title":"Blue Jodhpur","description":"Mehrangarh Fort at dawn, then the blue lanes below."},{"title":"Desert nights","description":"Sundowners on the dunes near Jaisalmer."}]}},{"id":"d1-places","type":"Place Chips","data":{"heading":"Key places","places":[{"name":"Jaipur","region":"Pink City"},{"name":"Udaipur","region":"Lakes"},{"name":"Jodhpur","region":"Blue City"},{"name":"Jaisalmer","region":"Desert"}]}},{"id":"d1-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"When is the best time to visit India?","answer":"Generally, October to March offers the most comfortable weather across the country. However, the Himalayas are best from May to September, and the monsoon (July-August) is beautiful in Kerala and Rajasthan."},{"question":"How many destinations should I include?","answer":"We recommend spending at least three to four nights in each place to truly absorb it. A two-week journey comfortably covers three or four regions at a relaxed pace."},{"question":"How do we travel between places?","answer":"A mix of private, chauffeur-driven cars for shorter distances and domestic flights for longer hops. We handle all the logistics seamlessly."}]}},{"id":"d1-cta","type":"CTA Banner","data":{"headline":"Your Rajasthan, your way","body":"Combine regions, or go deep into one.","buttonLabel":"Plan my Rajasthan journey","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"Rajasthan Travel | MANNYAM","description":"The India of the imagination. Warrior forts, lake palaces and bazaars that have traded for centuries.","canonical_url":"https://mannyam.in/destination-rajasthan"}$$::jsonb),

('Kerala', 'destination-kerala', 'Category', 'Published',
$$[{"id":"d2-hero","type":"Hero","data":{"headline":"Kerala","subheadline":"India at the pace of water. Palm lined backwaters, tea and spice hills and a gentle southern calm.","backgroundImage":"","ctaText":"Plan My Journey","ctaLink":"/enquire"}},{"id":"d2-facts","type":"Fact Bar","data":{"facts":[{"label":"Best season","value":"September to March"}]}},{"id":"d2-tiles","type":"Tiles","data":{"heading":"What you might do","tiles":[{"title":"On the water","description":"A private houseboat night with your own cook."},{"title":"Tea hills","description":"Walk the green slopes of Munnar with a grower."},{"title":"Old Kochi","description":"Harbour mornings among churches and fishing nets."}]}},{"id":"d2-places","type":"Place Chips","data":{"heading":"Key places","places":[{"name":"Kochi","region":"Harbour"},{"name":"Munnar","region":"Tea hills"},{"name":"Alleppey","region":"Backwaters"}]}},{"id":"d2-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"When is the best time to visit India?","answer":"Generally, October to March offers the most comfortable weather across the country. However, the Himalayas are best from May to September, and the monsoon (July-August) is beautiful in Kerala and Rajasthan."},{"question":"How many destinations should I include?","answer":"We recommend spending at least three to four nights in each place to truly absorb it. A two-week journey comfortably covers three or four regions at a relaxed pace."},{"question":"How do we travel between places?","answer":"A mix of private, chauffeur-driven cars for shorter distances and domestic flights for longer hops. We handle all the logistics seamlessly."}]}},{"id":"d2-cta","type":"CTA Banner","data":{"headline":"Your Kerala, your way","body":"Combine regions, or go deep into one.","buttonLabel":"Plan my Kerala journey","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"Kerala Travel | MANNYAM","description":"India at the pace of water. Palm lined backwaters, tea and spice hills and a gentle southern calm.","canonical_url":"https://mannyam.in/destination-kerala"}$$::jsonb),

('The Himalayas', 'destination-himalayas', 'Category', 'Published',
$$[{"id":"d3-hero","type":"Hero","data":{"headline":"The Himalayas","subheadline":"Some of the highest roads on earth, ancient monasteries and a stillness that stays with you.","backgroundImage":"","ctaText":"Plan My Journey","ctaLink":"/enquire"}},{"id":"d3-facts","type":"Fact Bar","data":{"facts":[{"label":"Best season","value":"May to September"}]}},{"id":"d3-tiles","type":"Tiles","data":{"heading":"What you might do","tiles":[{"title":"Monastery dawn","description":"Morning prayers at Thiksey before the day begins."},{"title":"High passes","description":"A careful drive over the world's great mountain roads."},{"title":"Night skies","description":"Stars so clear the Milky Way feels close."}]}},{"id":"d3-places","type":"Place Chips","data":{"heading":"Key places","places":[{"name":"Leh","region":"Ladakh"},{"name":"Nubra","region":"Valley"},{"name":"Spiti","region":"Highlands"}]}},{"id":"d3-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"When is the best time to visit India?","answer":"Generally, October to March offers the most comfortable weather across the country. However, the Himalayas are best from May to September, and the monsoon (July-August) is beautiful in Kerala and Rajasthan."},{"question":"How many destinations should I include?","answer":"We recommend spending at least three to four nights in each place to truly absorb it. A two-week journey comfortably covers three or four regions at a relaxed pace."},{"question":"How do we travel between places?","answer":"A mix of private, chauffeur-driven cars for shorter distances and domestic flights for longer hops. We handle all the logistics seamlessly."}]}},{"id":"d3-cta","type":"CTA Banner","data":{"headline":"Your The Himalayas, your way","body":"Combine regions, or go deep into one.","buttonLabel":"Plan my The Himalayas journey","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"The Himalayas Travel | MANNYAM","description":"Some of the highest roads on earth, ancient monasteries and a stillness that stays with you.","canonical_url":"https://mannyam.in/destination-himalayas"}$$::jsonb),

('Tamil Nadu', 'destination-tamil-nadu', 'Category', 'Published',
$$[{"id":"d4-hero","type":"Hero","data":{"headline":"Tamil Nadu","subheadline":"The heartland of living temple culture, with carved gateways that rise like mountains.","backgroundImage":"","ctaText":"Plan My Journey","ctaLink":"/enquire"}},{"id":"d4-facts","type":"Fact Bar","data":{"facts":[{"label":"Best season","value":"November to February"}]}},{"id":"d4-tiles","type":"Tiles","data":{"heading":"What you might do","tiles":[{"title":"Temple dawns","description":"Inside a working temple as the first prayers begin."},{"title":"Chettinad tables","description":"A long lunch in a heritage mansion."},{"title":"Coastal calm","description":"Slow days by the sea in Pondicherry."}]}},{"id":"d4-places","type":"Place Chips","data":{"heading":"Key places","places":[{"name":"Madurai","region":"Temples"},{"name":"Thanjavur","region":"Bronze"},{"name":"Pondicherry","region":"Coast"}]}},{"id":"d4-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"When is the best time to visit India?","answer":"Generally, October to March offers the most comfortable weather across the country. However, the Himalayas are best from May to September, and the monsoon (July-August) is beautiful in Kerala and Rajasthan."},{"question":"How many destinations should I include?","answer":"We recommend spending at least three to four nights in each place to truly absorb it. A two-week journey comfortably covers three or four regions at a relaxed pace."},{"question":"How do we travel between places?","answer":"A mix of private, chauffeur-driven cars for shorter distances and domestic flights for longer hops. We handle all the logistics seamlessly."}]}},{"id":"d4-cta","type":"CTA Banner","data":{"headline":"Your Tamil Nadu, your way","body":"Combine regions, or go deep into one.","buttonLabel":"Plan my Tamil Nadu journey","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"Tamil Nadu Travel | MANNYAM","description":"The heartland of living temple culture, with carved gateways that rise like mountains.","canonical_url":"https://mannyam.in/destination-tamil-nadu"}$$::jsonb),

('Varanasi & the Ganges', 'destination-varanasi', 'Category', 'Published',
$$[{"id":"d5-hero","type":"Hero","data":{"headline":"Varanasi & the Ganges","subheadline":"One of the oldest lived in cities on earth, and few places move a traveller more deeply.","backgroundImage":"","ctaText":"Plan My Journey","ctaLink":"/enquire"}},{"id":"d5-facts","type":"Fact Bar","data":{"facts":[{"label":"Best season","value":"October to March"}]}},{"id":"d5-tiles","type":"Tiles","data":{"heading":"What you might do","tiles":[{"title":"River at first light","description":"A quiet boat as the city bathes and prays."},{"title":"Evening fire","description":"A reserved view of the Ganga Aarti."},{"title":"The first sermon","description":"A calm morning at Sarnath nearby."}]}},{"id":"d5-places","type":"Place Chips","data":{"heading":"Key places","places":[{"name":"Varanasi","region":"The ghats"},{"name":"Sarnath","region":"Buddhist"}]}},{"id":"d5-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"When is the best time to visit India?","answer":"Generally, October to March offers the most comfortable weather across the country. However, the Himalayas are best from May to September, and the monsoon (July-August) is beautiful in Kerala and Rajasthan."},{"question":"How many destinations should I include?","answer":"We recommend spending at least three to four nights in each place to truly absorb it. A two-week journey comfortably covers three or four regions at a relaxed pace."},{"question":"How do we travel between places?","answer":"A mix of private, chauffeur-driven cars for shorter distances and domestic flights for longer hops. We handle all the logistics seamlessly."}]}},{"id":"d5-cta","type":"CTA Banner","data":{"headline":"Your Varanasi & the Ganges, your way","body":"Combine regions, or go deep into one.","buttonLabel":"Plan my Varanasi & the Ganges journey","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"Varanasi & the Ganges Travel | MANNYAM","description":"One of the oldest lived in cities on earth, and few places move a traveller more deeply.","canonical_url":"https://mannyam.in/destination-varanasi"}$$::jsonb),

('The North-East', 'destination-north-east', 'Category', 'Published',
$$[{"id":"d6-hero","type":"Hero","data":{"headline":"The North-East","subheadline":"India's best kept secret. A green world of root bridges, clear rivers and proud tribal cultures.","backgroundImage":"","ctaText":"Plan My Journey","ctaLink":"/enquire"}},{"id":"d6-facts","type":"Fact Bar","data":{"facts":[{"label":"Best season","value":"October to April"}]}},{"id":"d6-tiles","type":"Tiles","data":{"heading":"What you might do","tiles":[{"title":"Root bridges","description":"Walk to bridges grown, not built, over generations."},{"title":"Village welcome","description":"Time with a Khasi or Naga family in the hills."},{"title":"Tea and rhino","description":"An Assam garden stay paired with Kaziranga."}]}},{"id":"d6-places","type":"Place Chips","data":{"heading":"Key places","places":[{"name":"Shillong","region":"Meghalaya"},{"name":"Kaziranga","region":"Assam"},{"name":"Nagaland","region":"Hills"}]}},{"id":"d6-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"When is the best time to visit India?","answer":"Generally, October to March offers the most comfortable weather across the country. However, the Himalayas are best from May to September, and the monsoon (July-August) is beautiful in Kerala and Rajasthan."},{"question":"How many destinations should I include?","answer":"We recommend spending at least three to four nights in each place to truly absorb it. A two-week journey comfortably covers three or four regions at a relaxed pace."},{"question":"How do we travel between places?","answer":"A mix of private, chauffeur-driven cars for shorter distances and domestic flights for longer hops. We handle all the logistics seamlessly."}]}},{"id":"d6-cta","type":"CTA Banner","data":{"headline":"Your The North-East, your way","body":"Combine regions, or go deep into one.","buttonLabel":"Plan my The North-East journey","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"The North-East Travel | MANNYAM","description":"India's best kept secret. A green world of root bridges, clear rivers and proud tribal cultures.","canonical_url":"https://mannyam.in/destination-north-east"}$$::jsonb),

('Gujarat', 'destination-gujarat', 'Category', 'Published',
$$[{"id":"d7-hero","type":"Hero","data":{"headline":"Gujarat","subheadline":"India's most surprising and least crowded state. White salt deserts and extraordinary craft.","backgroundImage":"","ctaText":"Plan My Journey","ctaLink":"/enquire"}},{"id":"d7-facts","type":"Fact Bar","data":{"facts":[{"label":"Best season","value":"November to February"}]}},{"id":"d7-tiles","type":"Tiles","data":{"heading":"What you might do","tiles":[{"title":"White desert","description":"An evening on the salt flats as the light turns."},{"title":"Craft villages","description":"Days among master weavers and embroiderers."},{"title":"Wild lions","description":"A careful safari in Gir, their last refuge."}]}},{"id":"d7-places","type":"Place Chips","data":{"heading":"Key places","places":[{"name":"Kutch","region":"Salt desert"},{"name":"Ahmedabad","region":"Old city"},{"name":"Gir","region":"Lions"}]}},{"id":"d7-faq","type":"FAQ","data":{"heading":"Questions, answered simply","items":[{"question":"When is the best time to visit India?","answer":"Generally, October to March offers the most comfortable weather across the country. However, the Himalayas are best from May to September, and the monsoon (July-August) is beautiful in Kerala and Rajasthan."},{"question":"How many destinations should I include?","answer":"We recommend spending at least three to four nights in each place to truly absorb it. A two-week journey comfortably covers three or four regions at a relaxed pace."},{"question":"How do we travel between places?","answer":"A mix of private, chauffeur-driven cars for shorter distances and domestic flights for longer hops. We handle all the logistics seamlessly."}]}},{"id":"d7-cta","type":"CTA Banner","data":{"headline":"Your Gujarat, your way","body":"Combine regions, or go deep into one.","buttonLabel":"Plan my Gujarat journey","buttonLink":"/enquire"}}]$$::jsonb,
$${"title":"Gujarat Travel | MANNYAM","description":"India's most surprising and least crowded state. White salt deserts and extraordinary craft.","canonical_url":"https://mannyam.in/destination-gujarat"}$$::jsonb);

